# Build on supported Pythons
#
# Closely watch version references for actions!

name: R build and check

on: [push, pull_request]

jobs:
  R_CMD_check:
    name: ${{ matrix.config_os }} (${{ matrix.config.r }})
    runs-on: ${{ matrix.config.os }}
    strategy:
      fail-fast: false
      matrix:
        config:
          - {os: macOS-latest, r: "release"}
          - {os: windows-latest, r: "release"}
          - {os: ubuntu-latest, r: "devel", http-user-agent: "release"}
          - {os: ubuntu-latest, r: "release"}
          - {os: ubuntu-latest, r: "oldrel-1"}
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      R_KEEP_PKG_SOURCE: yes

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup pandoc
        uses: r-lib/actions/setup-pandoc@v2

      - name: Setup R
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: ${{ matrix.config.r }}
          http-user-agent: ${{ matrix.config.http-user-agent }}
          use-public-rspm: true

      - name: Install required R packages
        uses: r-lib/actions/setup-r-dependencies@v1
        with:
          extra-packages: |
            knitr
            lattice
            pander
            rmarkdown
            tinytest
            geosphere
            KernSmooth
            plotly
            quantreg
            uniReg
            rcmdcheck

      - name: Check package
        uses: r-lib/actions/check-r-package@v2

      - name: Show testthat output
        if: always()
        run: find check -name 'testthat.Rout*' -exec cat '{}' \; || true
        shell: bash

      - name: Upload check results
        if: failure()
        uses: actions/upload-artifact@v3
        with:
          name: ${{ runner.os }}-r${{ matrix.config.r }}-results
          path: check
